title: Jennifer's Portfolio
email: jenpaff0@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Woman in Tech who is passionate about building high quality software together in a team.
baseurl:
url: https://www.jennifer-codes.com # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: https://www.jennifer-codes.com
twitter_username: '@jenpaff'
github_username:  jenpaff

seo:
  description: 'Software Engineer. Passionate about delivering high quality software & embracing diversity in the tech industry'
  author: 'Jennifer Parak'

#port: 443

include: ['_includes/portfolio']

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
